os:
  - linux

language: go
sudo: false

go:
  - tip
  - 1.9

before_install:
  - make deps

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - tiago.katcipis@neoway.com.br
